python3 ./compile.py -R 32 poplar-efficiency IRIS
python3 ./compile.py -R 32 poplar-efficiency wine
python3 ./compile.py -R 32 poplar-efficiency cancer
python3 ./compile.py -R 32 poplar-efficiency tic-tac-toe
python3 ./compile.py -R 32 poplar-efficiency kohkiloyeh
python3 ./compile.py -R 32 poplar-efficiency diagnosis
python3 ./compile.py -R 32 poplar-efficiency digits
python3 ./compile.py -R 32 poplar-efficiency adult
#python3 ./compile.py -R 32 poplar-efficiency Skin_NonSkin
