python3 ./compile.py -R 32 poplar-accuracy IRIS
python3 ./compile.py -R 32 poplar-accuracy wine
python3 ./compile.py -R 32 poplar-accuracy cancer
python3 ./compile.py -R 32 poplar-accuracy tic-tac-toe
python3 ./compile.py -R 32 poplar-accuracy kohkiloyeh
python3 ./compile.py -R 32 poplar-accuracy diagnosis
python3 ./compile.py -R 32 poplar-accuracy digits
python3 ./compile.py -R 32 poplar-accuracy adult
python3 ./compile.py -R 32 poplar-accuracy Skin
